README.md
ios/RNWifi.m

iOS 13+ users can use connectToProtectedSSIDPrefix and connectToSSIDPrefix when they want to match a known SSID prefix, but don’t have a full SSID. If the device finds multiple Wi-Fi networks whose SSID string matches the given prefix, it selects the network with the greatest signal strength.
Added connectToProtectedSSIDPrefix and connectToSSIDPrefix to README, and fixed "isWeb" to "isWep" in documentation with detailed explanation.

Connect to SSID prefix functions.

---

android/src/main/java/com/reactlibrary/rnwifi/RNWifiModule.java
ios/RNWifi.m

There was an issue when connecting to an **already failed connection** where `enableNetwork()` returned always `true` because of its non-blocking nature.
There was an issue where `NEHotspotConfigurationManager` returned no error if the device could connect to another SSID quickly enough. (#23)
Implemented a `BroadcastReceiver` to verify that connection has been successfully established.
Implemented a check for the current SSID after `NEHotspotConfigurationManager` returns. (Fixes: #23).

fix: Verify connection after enabling network

---

ios/RNWifi.m

Implemented joinOnce for connectToSSIDPrefix, this is to match the already merged PR changes in `connectToProtectedSSID` and https://github.com/JuanSeBestia/react-native-wifi-reborn/pull/33

fix(iOS): Fix joinOnce for connectToSSIDPrefix 

---

README.md
android/build.gradle
android/src/main/java/com/reactlibrary/rnwifi/RNWifiModule.java

Starting Android 10, it's no longer possible to connect (as an app) to wifi networks like before.
What can an app still do:
Temporary connect to a wifi access point (for example to setup an IoT device)
Suggest a network, but the OS can choose what to do with it.
With this PR, i've switched the connection logic to use WifiUtils which just released support for option 1.
Advantages of using WifiUtils:
Works well on different android versions
Only resolves when the app is connected to the network
Has a good retry mechanism built in
Well written code

BREAKING CHANGE: Use WifiUtils to connect with a wifi network

---

README.md
android/src/main/java/com/reactlibrary/rnwifi/ForceWifiUsageErrorCodes.java
android/src/main/java/com/reactlibrary/rnwifi/RNWifiModule.java
lib/types/index.d.ts

The previous implementation of forceWifiUsage() used SYSTEM_WRITE_SETTINGS that requires the user to accept that the app may change system settings, but it is actually not required to force api calls going to the wifi network.
Improved code, updated readme & updated typescript.

feat: Less restrictive forceWifiUsage

---

lib/types/index.d.ts

Solve typescript type checking issue for the function `connectToProtectedSSID `

fix: Add null type to password on connectToProtectedSSID

---

README.md
_config.yml
android/src/main/java/com/reactlibrary/rnwifi/IsEnabledErrorCodes.java
android/src/main/java/com/reactlibrary/rnwifi/RNWifiModule.java
android/src/main/java/com/reactlibrary/rnwifi/receivers/WifiScanResultReceiver.java
lib/types/index.d.ts

Use a promise instead of the callback mechanism. Readme + typescript definition also updated.

BREAKING CHANGE: Use promises instead of callbacks

---

ios/RNWifi.m

This setting in the `connectToProtectedSSIDPrefix` was inconsistent with the other functions for no reason. It was already discussed why it should be set to `false`. https://github.com/JuanSeBestia/react-native-wifi-reborn/issues/2
However, in my opinion we should let the user of this module decide the values for `joinOnce` and `lifeTimeinDays`. If we all agree on that it should be done in another PR.
https://developer.apple.com/documentation/networkextension/nehotspotconfiguration

fix(iOS): Consistent joinOnce=false configuration

---

lib/types/index.d.ts

Also, remove redundant (incorrect) parse example for loadWifiList.

fix: Fix reScanAndLoadWifiList() return type

---

README.md
android/src/main/java/com/reactlibrary/rnwifi/RNWifiModule.java
lib/types/index.d.ts

Removes NET_CAPABILITY_INTERNET when indicated via noInternet so android phones with intelligent wifi switching are less eager to switch to a different wifi network.
Inspiration from: https://github.com/JuanSeBestia/react-native-wifi-reborn/pull/109 🎉.

feat(Android): Add forceWifiUsageWithOptions & add noInternet option

---

android/build.gradle
android/gradle/wrapper/gradle-wrapper.properties

Dependency WifiUtils 1.6.3 had some issues with their dependencies. They've released a new version to fix this.

fix(Android): Fix WifiUtils dependencies

---

android/src/main/java/com/reactlibrary/rnwifi/RNWifiModule.java
android/src/main/java/com/reactlibrary/rnwifi/mappers/WifiScanResultsMapper.java
android/src/main/java/com/reactlibrary/rnwifi/receivers/WifiScanResultReceiver.java
android/src/main/java/com/reactlibrary/rnwifi/utils/LocationUtils.java
android/src/main/java/com/reactlibrary/rnwifi/utils/PermissionUtils.java

The mappers and receivers are not in the com.reactlibrary.rnwifi package.

chore(Android): Move mappers and receivers

---

android/build.gradle

To fix the dependency bug reported here: https://github.com/JuanSeBestia/react-native-wifi-reborn/issues/142  we can add 'com.thanosfisherman.elvis:elvis:3.0' in the libs build.gradle for now.
I'll follow up with WifiUtils. On some devices there are no problems (Samsung S10) and on others there are (OnePlus NORD) so I think it might be cpu architecture related.
Fixes #142

fix(Android): Add elvis dependency to build.gradle

---

README.md
android/src/main/java/com/reactlibrary/rnwifi/RNWifiModule.java
android/src/main/java/com/reactlibrary/rnwifi/errors/GetCurrentWifiSSIDErrorCodes.kt
lib/types/index.d.ts

Sometimes while switching network, android returns <unknown ssid>.
You aren't connected, so let's simply return an empty string.

fix(Android): getCurrentWifiSSID return null if '<unknown ssid>'

---

android/src/main/java/com/reactlibrary/rnwifi/errors/GetCurrentWifiSSIDErrorCodes.java
android/src/main/java/com/reactlibrary/rnwifi/errors/GetCurrentWifiSSIDErrorCodes.kt

As reported here; https://github.com/JuanSeBestia/react-native-wifi-reborn/issues/153, mixing kotlin with java breaks building apps. Let's stick to using Java for now.

fix(Android): Replace Kotlin files with Java

---

ios/RNWifi.m

Closes #182
I tested the proposed idea (similar to what is done when connecting to a protected network with the full SSID, verify the connection after connecting only with a prefix provided) I had from looking at the source code and could confirm that this indeed fixes the issue of `connectToProtectedSSIDPrefix` not rejecting when the connection was not successful. The system alert does still appear, but the method properly rejects.
I tested this change with an app on my iPhone with iOS 14.4. Are there any additional tests/steps I should perform?
Thanks for your support!

fix(iOS): reject after connecting to WiFi with SSID-prefix

---

README.md
ios/RNWifi.m
lib/types/index.d.ts

Exposes the option to set `joinOnce` on iOS methods. Documentation is verbatim from Apple's page https://developer.apple.com/documentation/networkextension/nehotspotconfiguration/2887518-joinonce.
I made an effort to ensure backwards compatibility with the previous functions by overloading them and re-using the implementations.
Please let me know if I totally messed this up or need to do any additional steps. I've been using this package for a while but this is my first time contributing. Thank you @JuanSeBestia & others for your great work!
https://github.com/JuanSeBestia/react-native-wifi-reborn/pull/72 added `joinOnce=false` and mentioned adding this feature.

feat(iOS): allow joinOnce property to be set for iOS devices

---

ios/RNWifi.m

Fixes https://github.com/JuanSeBestia/react-native-wifi-reborn/issues/17
I tested locally for iOS 15 on a wifi network that the app configured and calling disconnect directly works. But with the `getConfiguredSSIDsWithCompletionHandler` it does not.
This is an alternative to: https://github.com/JuanSeBestia/react-native-wifi-reborn/pull/213

fix(iOS): Fix disconnectFromSSID having no effect

---

android/build.gradle

jCenter is shutting down (https://blog.gradle.org/jcenter-shutdown). Android dependency WifiUtils is now published on mavenCentral 👏 so it's time to switch! React-native 65 also makes the switch to mavenCentral (https://github.com/facebook/react-native/releases/tag/v0.65.0).
* replace jCenter repository with mavenCentral
* change WifiUtils artifact id name to `io.github.thanosfisherman.wifiutils` and bump dependency to 1.6.6 (https://github.com/ThanosFisherman/WifiUtils/releases/tag/WifiUtils1.6.6)
* remove peer dependency Elvis (no longer required: https://github.com/ThanosFisherman/WifiUtils/releases/tag/WifiUtils1.6.4)

fix(Android): Replace jCenter with mavenCentral

---

ios/RNWifi.m

This PR corrects the SSID check in the connectToProtectedSSIDPrefix by ensure that the new SSID has the prefix provided by the user instead of checking if the new SSID is equal to that.

fix(iOS): Fix prefix check in connectToProtectedSSIDPrefix

---

ios/RNWifi.m

In https://github.com/JuanSeBestia/react-native-wifi-reborn/pull/214 a bug was fixed regarding `disconnectFromSSID` having no effect. However, I'm pretty sure the `resolve(nil)` was wrongly removed. In our code, the promise now never resolves.
This PR reverts that unwanted deletion and makes sure the (JS) promise resolves.
Tested with our code.

fix(iOS): Revert wrong removal of promise resolution

---

.eslintignore
.eslintrc.json
README.md
app.plugin.js
ios/RNWifi.m
package-lock.json
package.json
plugin/dist/withWifi.d.ts
plugin/dist/withWifi.js
plugin/src/withWifi.ts
plugin/tsconfig.json

> Heavily inspired by https://github.com/react-native-voice/voice/pull/317
This PR adds integration with Expo's [Config Plugins](https://docs.expo.io/guides/config-plugins/) which let users add native modules that aren't in the Expo Go app to their native cloud builds and locally [when prebuilding](https://expo.fyi/prebuilding).
If you'd rather not maintain an Expo integration, I understand and hope this remnant PR is instructional for future Expo users!
* Added a `/plugin` folder and an `app.plugin.js` as the main entry point to the plugin
The plugin is like a different package that's vendored for versioning purposes.
* Building is done with `tsc --build plugin` (`yarn build:plugin`).
* Tested by running `expo prebuild` (with & without `Props`) and seeing the native config appear …

feat: Add Expo config plugin

---

lib/types/index.d.ts

When running `npx tsc` on my project, with `skipLibCheck` set to `false` in our `tsconfig.json` (which is the default anyway). The following TS errors were reported:
This PR fixes these two issues by exposing `DISCONNECT_ERRORS` and `IS_REMOVE_WIFI_NETWORK_ERRORS` as proper `enum` types.

fix: Use enum types instead of const in the TypeScript declaration file

---

android/src/main/java/com/reactlibrary/rnwifi/RNWifiModule.java
lib/types/index.d.ts

I was using react-native-wifi-reborn for a project that needed the feature to connect to a device with a hidden WiFi. With these changes, I was able to connect to the device using `WifiManager.connectToProtectedSSID` (with Android 10+).

feat(Android): added feature to connect to hidden wifi on android 10

---

android/build.gradle
android/gradle/wrapper/gradle-wrapper.properties

* replace jCenter with mavenCentral
* bump android gradle plugin
* bump gradle-wrapper
* use safeExtGet to get min, compile & sdk versions from app

Android Tooling

---

android/src/main/java/com/reactlibrary/rnwifi/mappers/WifiScanResultsMapper.java

Just a simple java change; don't mutate the ScanResults, just populate the WritableNativeArray correctly.

fix: prefer not to mutate the ScanResult object

---

android/src/main/java/com/reactlibrary/rnwifi/RNWifiModule.java

The `setEnabled()` function is deprecated on Android 10 and above, and it appears not to work on Android 13.
The recommended solution is to utilize the `Settings.Panel.ACTION_WIFI` on these versions.

fix(Android): Open the Wifi settings panel on Android 10 and above.

---

README.md
android/src/main/java/com/reactlibrary/rnwifi/RNWifiModule.java
example/with-expo/components/ConnectToSSID.tsx
ios/RNWifi.m
lib/types/index.d.ts

In this PR, a timeout parameter has been added to the connectToProtectedWifiSSID method.
The parameter, as methods are made today, is mandatory. If set to null then by default it will use a 15 second timeout for the connection. The parameter is to be used in seconds and not in milliseconds, the conversion is done in the method.
The timeout was added only for Android, as I didn't encounter any problems on IOS.
This PR was created because, when we try to connect to a network by entering an incorrect password, the ANDROID system takes too long to return a response.

ANDROID: Timeout parameter on connectToProtectedSSID method

---

android/src/main/java/com/reactlibrary/rnwifi/RNWifiModule.java

Hi,
with the last release I forgot to add a check on the isHidden parameter.
this generates a crash if it is not passed.
I created this PR to solve the problem immediately.
@JuanSeBestia @gustavoabel 
Thank you

fix: crash on Android when isHidden params not passed

---

package-lock.json
package.json

When I cloned the repo I couldn't run `npm install` due to:
```
[12:06:40] dave@DaveXPS:~/projects/react-native-wifi-reborn$ npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @semantic-release/changelog@3.0.4
npm ERR! Found: semantic-release@19.0.3
npm ERR! node_modules/semantic-release
npm ERR!   dev semantic-release@"^19.0.3" from the root project
npm ERR!   peer semantic-release@">=18.0.0-beta.1" from @semantic-release/commit-analyzer@9.0.2
npm ERR!   node_modules/@semantic-release/commit-analyzer
npm ERR!     @semantic-release/commit-analyzer@"^9.0.2" from semantic-release@19.0.3
npm ERR!   3 more (@semantic-release/github, @semantic-release/npm, @semantic-release/release-notes-generator)
npm ERR! 
npm ERR! Could not resolve …
```

chore(deps-dev): update semantic-release packages

---

android/src/main/java/com/reactlibrary/rnwifi/RNWifiModule.java
lib/types/index.d.ts

Implements wifi network suggestion from this documentation:
[https://developer.android.com/develop/connectivity/wifi/wifi-suggest](https://developer.android.com/develop/connectivity/wifi/wifi-suggest)
- Tested on android 14
Suggestions are welcome :)

WifiNetworkSuggestion API for android 10 and above.

---

README.md
ios/RNWifi.m

Fix #396 
Fix #379 
I honestly don't know if this is correct, I used [this conversation with ChatGPT](https://chatgpt.com/share/c7ba66de-ee88-4583-aa86-f9a08635b249) to help me fix this error.
This PR absolutely requires at least one review from someone that know this code and language.
cc @JuanSeBestia @alexma01

fix: set timeout param for iOS as nonnull instead of nullable, as React requires

---

README.md

The current section for iOS setup makes a lot of people encounter problems when they received error on cannot detect SSID or failed to connect to Wi-Fi, this fix should able to make it more clear for iOS XCode setup.
Image credits to @eliottparis on #385

docs: fix unclear wifi section

---

README.md

There's a mildly confusing mention of `connectToProtectedWifiSSID` in the README docs, while otherwise only mentioning `connectToProtectedSSID`. This PR clears it up. Both seem to exist in the actual code, and support the same arguments, but I think being consistent would be better?

Tweak README.md example - consistently use connectToProtectedSSID

---

android/src/main/java/com/reactlibrary/rnwifi/RNWifiModule.java

pollForValidSSID is checking if network is 'something', which might just be connecting so it fails to actually wait for a proper connection to be realized - tested with `examples/with-expo` demo on Android 8

fix(Android): properly check on pollForValidSSID if network connected

---

README.md

To use local networks, you must add the NSLocalNetworkUsageDescription to your iOS app's Info.plist

Update README.md to include NSLocalNetworkUsageDescription

---

android/src/main/java/com/reactlibrary/rnwifi/RNWifiModule.java

This fixes an issue where connections to IoT devices (and probably other regular networks too) would fail because `pollForValidSSID()` was using incorrect connection status checking method for per-app connections.
This issue occurs because `getConnectionStatus` checks only the status of the "main" WiFi state. When connected via a "per-app" connection, calling `getState` within `getConnectionStatus` returns `DISCONNECTED`, and `wifiInfo.isConnected()` returns `false`. However, this doesn't reflect the actual situation, as the established connection is functioning correctly.
Modified `getConnectionStatus()` to properly handle per-app WiFi connections on Android 10+ by:
- Using `joinedNetwork` reference for checking connection instead of "main" WiFi
- Adding proper checks to ensure network …

fix(android): connection status support for per-app wifi connections

---

ios/RNWifi.m

When a user denies the WiFi connection prompt on iOS, the app crashes without any error message. This happens when calling `connectToProtectedSSID`.
This fixes #424 
XCode's catched crash error:
```
Thread 1: EXC_BAD_ACCESS (code=1, address=0x10)
```
The iOS implementation includes a timeout parameter that isn't used and isn't defined in TypeScript types:
TypeScript definition:
```typescript
connectToProtectedSSID(
ssid: string, 
password: string, 
isWEP: boolean, 
isHidden: boolean
): Promise<void>;
```
Native method implementation:
```objc
RCT_EXPORT_METHOD(connectToProtectedSSID:(NSString*)ssid
withPassphrase:(NSString*)passphrase
isWEP:(BOOL)isWEP
isHidden:(BOOL)isHidden
timeout:(nonnull NSNumber *)timeout // Extra parameter
resolver:(RCTPromiseResolveBlock)resolve …
```

Remove unused timeout parameter from iOS WiFi connection methods

---

lib/types/index.d.ts
src/index.js

When starting to use this library last week, I noticed that the autocompletion/intellisense in VS Code did not pick up the module functions properly.
This PR attempts to fix this and align the types in index.d.ts with the native interface, as follows:
index.d.ts:
Move the function definitions inside an interface block, to better align with the native module interface as follows:
```typescript
interface WifiManagerStatic {
<functions>
}
var WifiManager: WifiManagerStatic;
export default WifiManager;
```
This means that doing WifiManager._tab_ now gives the list of available functions.
index.js:
Some of the error enum entries were missing from index.js, so this aligns them to index.d.ts and native code.
index.d.ts:
Added a few description comments to enums and functions, where they were not …

fix(types): Align types, index and native module interfaces

---

ios/RNWifi.m

I took [SynidSweet](https://github.com/SynidSweet)'s suggestion from https://github.com/JuanSeBestia/react-native-wifi-reborn/issues/429 and created a PR.
Fixes #429

fix: add a flag to track completion status in connectToProtectedSSIDOnce
